# Generated by Django 3.0.5 on 2021-10-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0002_joinedevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinedevent',
            name='sid',
            field=models.IntegerField(),
        ),
    ]
