# Generated by Django 3.0.5 on 2021-10-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0003_auto_20211014_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinedevent',
            old_name='sid',
            new_name='stud_id',
        ),
    ]
