# Generated by Django 3.0.5 on 2021-10-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0004_auto_20211014_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinedevent',
            name='stud_id',
        ),
        migrations.AddField(
            model_name='joinedevent',
            name='s_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
