# Generated by Django 3.0.5 on 2021-10-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0005_auto_20211014_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinedevent',
            name='eid',
        ),
        migrations.AddField(
            model_name='joinedevent',
            name='e_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
