# Generated by Django 3.0.5 on 2021-10-13 20:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0006_auto_20211014_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedEv',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s_id', models.IntegerField()),
                ('e_id', models.UUIDField()),
            ],
        ),
        migrations.DeleteModel(
            name='JoinedEvent',
        ),
    ]
