# Generated by Django 3.0.5 on 2021-10-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0007_auto_20211014_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedev',
            name='ename',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
