# Generated by Django 3.0.5 on 2021-10-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0008_joinedev_ename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinedev',
            name='ename',
            field=models.CharField(max_length=100),
        ),
    ]
