# Generated by Django 3.0.5 on 2021-10-19 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0009_auto_20211014_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2021, 10, 19)),
        ),
    ]
